### ISSUE TITLE
does not run

### ISSUE THREAD

**Issue by aryamanarora** [papplampe/Victoria2Generator#1]
reproduction:

```bash
aryaman-arora:Generator aryaman.arora$ python Generator.py 

You can customize some variables by editing the Settings.ini file.

Traceback (most recent call last):
  File "Generator.py", line 2203, in <module>
    Main()
  File "Generator.py", line 2003, in Main
    Startup()
  File "Generator.py", line 1076, in Startup
    ModName += CreateModName()
  File "Generator.py", line 1042, in CreateModName
    Name = Name.replace("$city$",NameGen.GeneratePlaceName(RandomDict,0))
  File "/Applications/Victoria 2.app/Generator/NameGen.py", line 91, in GeneratePlaceName
    Dictionary1 = open("Generator/CultureGroups/"+DictionaryName+".names1").readlines()
FileNotFoundError: [Errno 2] No such file or directory: 'Generator/CultureGroups/Generator/CultureGroups/Nahuatl.names1'
```

**Comment by henkman** [comment]
Going by your github profile you seem to be able to deal with this issue. I suggest checking why DictionaryName contains the CultureGroups directory
